services:
  app:
    build:
      context: .
      args:
        - PORT
    command: sh -c "yarn start:prod"
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT=${PORT}
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: ['redis-server']
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
volumes:
  pgdata:
